name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build_backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '20'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
        working-directory: backend

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: build_backend
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend
  
      - name: Build frontend
        run: npm run build
        working-directory: frontend

    test_backend:
      name: Run backend tests
      runs-on: ubuntu-latest
      needs: build_frontend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: risRecepti
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
		■  5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
	○  name: Checkout repository
        uses: actions/checkout@v3

	○  name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '20'
          cache: maven

	○  name: Run backend tests
        run: mvn test
        working-directory: backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/risRecepti
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
